version: '3'

services:
  brave-search-mcp:
    build:
      context: .
      dockerfile: Dockerfile.simple
    environment:
      - BRAVE_API_KEY=${BRAVE_API_KEY}
      - TRANSPORT=sse
      - PORT=3000
    ports:
      - "3000:3000"
    restart: unless-stopped